import =  [
"~/.config/alacritty/themes/tokyo-night.toml"
]

[window]
dimensions = { columns = 100, lines = 30}
position = { x = 460, y = 230}
dynamic_padding = false
# decorations = "Transparent" #(macOS only)
opacity = 0.9
dynamic_title = true
option_as_alt = "Both" #(macos only)
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

size = 18
