import =  [
"~/.config/alacritty/themes/tokyo-night.toml"
]

[env]
term = "xterm-256color"

[window]
dimensions = { columns = 100, lines = 30}
position = { x = 220, y = 200}
dynamic_padding = false
# decorations = "Transparent" #(macOS only)
decorations = "Buttonless"
opacity = 0.9
blur = true
dynamic_title = true
option_as_alt = "Both" #(macos only)
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

size = 20

[colors]
cursor = { text = "CellBackground", cursor = "#2efe98" }


